packages:
  - '.'

allowBuilds:
  '@prisma/engines': set this to true or false
  bcrypt: set this to true or false
  esbuild: set this to true or false
  prisma: set this to true or false

overrides:
  nodemailer@<7.0.7: '>=7.0.7'
  nodemailer@<8.0.4: '>=8.0.4'
  nodemailer@<=7.0.10: '>=7.0.11'
  nodemailer@<=8.0.4: '>=8.0.5'
  tar@<7.5.7: '>=7.5.7'
  tar@<7.5.8: '>=7.5.8'
  tar@<=7.5.10: '>=7.5.11'
  tar@<=7.5.2: '>=7.5.3'
  tar@<=7.5.3: '>=7.5.4'
  tar@<=7.5.9: '>=7.5.10'
